language: node_js
node_js:
  - "8"
env:
  DOCKER_USERNAME:
    secure: "JSOo4Uwa4CZPB9pef6XMlFBCSvvoXAoaLZgKV3VqX4+WeqhKi7Eh0R3u547gKzIdJbH8uGVae7VrEQA+B9VadO44vjli+7UmZ7SFE+LVEWzXndRmwDFx6bwSDfpfyHAi4HKN4str59aLfUZ2MZgD2GU4aWRRcAV1YvV/5Yt/ItDYmVppT3uZjLVxRoiI2Ru8q+UIYClGmxGKGacFGos1WyddqT5MHEdL5yBzxEI9Ik/0eYEPna7LrTdLhZTpdTlLXRLs76ECBzNBdedDte24K6Mo+SOxqqQObWQ2Sr6VkugmSHmhHBLVqj6V9mvCF0EdZqC5PYil5gb3rPwumOCgGBRBPP6zK7cGoQmJoiRsBOxfFu8fgEeW2V85VyLSJ3PlBJyUSK9en1cYzuAbNQRsMgJ0Nnv+hyfzSjuE/SwWjmEQGqMEVUDUoFgiAFa2PZFRF0FkD2raj37JPOfxWXqn4PAF3kDQtj0PtJfbRObEUcdqV2QGaMlxK/sY9i0d/7BN77ZGx7Ztd9Tbm6Rks317+9fZJFzDkM1Fnbsm/mX25X4oEDRwhEc4bRj5y9YSVeO1UJu8ZJjmN4vd23BD7tfFQoS2Ga0AHB75DG6RRvot0JDkmzs3oQ39DpU+iGhGWztlAVMSxDa1klbRRkJmu5hGYBixLX9Ps6W6f8R87/hoHYc="
  DOCKER_PASSWORD:
    secure: "ZKzEupYDlY8/zSuweDeB2U+n3GrxXykh2mlJzO4FXTHpMYcRSo2VhT8E3GUUF4OYIWTmSqDdqiKEGHG5KpcoZDcVr7jRIY3yi7EpWYJDwc72EdDWwLp/dktpVFk7Nn6kH9jyW2fP7kjzdl/Z+I2E2cLDd+NsHACQr7yDkqJo/Xh4j8/ZuZ1245tVZ4S5kyFTGE19xGgJXXHs82qDSoc4W+u75tI+aBdcmYKIRlBQbU9kedCmhvOe8iUPTvCh1Ah7rigQ+g5nxoOcpgVArlpJfGXnsSmYO257t06wUYp68X3gL9znQkNfDKRLivUjCQnF2M7uDzgGAzEca0BZjYNRfBV6ko0eAl9EDwJbovYQbNtJYmRhmngbTDiCMZDvdwm+j+Hs6FQ9So6q3C0lLloNiGtD0O2u2JYp3g3M1lNm925x01f/9DJ+qJOBCmC5s6z6AAHLMf/QPpDU2TSTZ20UpvfaWECGAjtg2JuXBXUsW8nLRR1lZDVzfmQmei9L70/IZquFfz3oVw4+LeU7yDB38mX3jHRyIvkoKuHizJ/9KSSRXbd0wg8Y/avLt9NCGAzbIyOrC76FewKLgOIp6QR9sAkhSa+q0FqzHJR6tQJ7ZhJzluCMrRQVo9NSYLdHp5DVXJ34KpbZyLmSxp0OtfcGKcUfwEZaw7+X2UFDh9Oi3E4="
#cache:
  #directories:
  #  - node_modules
  #yarn: true
install:
  - yarn install --pure-lockfile
  - npm run contracts-compile
#script:
  #- npm test
after_success:
  docker build -t dx-services .;
  docker login -u "$DOCKER_USERNAME" -p "$DOCKER_PASSWORD";
  
  if [ "$TRAVIS_BRANCH" == "master" ]; then
    docker tag dx-services gnosispm/dx-services:$TRAVIS_BRANCH;
    docker push gnosispm/dx-services:$TRAVIS_BRANCH;
  elif [ "$TRAVIS_BRANCH" == "development" ]; then
    docker tag dx-services gnosispm/dx-services:development;
    docker push gnosispm/dx-services:development;
  fi
