version: '3.4'

services:
  ethereum:
    hostname: ethereum
    image: trufflesuite/ganache-cli:latest
    command: ganache-cli -d --mnemonic 'candy maple cake sugar pudding cream honey rich smooth crumble sweet treat' --defaultBalanceEther '500'
    ports:
      - "8545:8545"
    # networks:
    #   - webnet

  setup:
    command: npm run setup
    build:
      context: '.'
    depends_on:
      - ethereum
    links:
      - ethereum
    network_mode: 'host'
    # TODO: use links, provide the url by param, and override the truffle.js file
    environment:
      ETHEREUM_RPC_URL: http://ethereum:8545
    #volumes:
    #  - .:/usr/src/app
    # networks:
    #   - webnet

  # TODO: Wait for setup to run. Script or let the app handle retries
  api:
    command: npm run api
    hostname: dx
    build:
      context: '.'
    depends_on:
      - setup
    # links:
    #   - ethereum
    environment:
      #ETHEREUM_RPC_URL: http://ethereum:8545
      ETHEREUM_RPC_URL: http://localhost:8545
    # volumes:
    #   - .:/usr/src/app
    network_mode: 'host'
    ports:
      - "3000:8080"
    # networks:
    #   - webnet

  # TODO: Wait for setup to run. Script or let the app handle retries
  # bots:
  #   command: npm run bots-script
  #   hostname: bots
  #   build:
  #     context: '.'
  #   depends_on:
  #     - setup
  #     - ethereum
  #   ports:
  #     - "3001:8081"
  #   volumes:
  #     - .:/usr/src/app
  #   networks:
  #     - webnet
      
# networks:
#   webnet: